apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rds-rest-api-v2
  description: Daňové subjekty REST API v2
  tags:
    - rest
  links:
    - url: https://registr.cz/api/v2
      title: PROD
    - url: https://registr-test.cz/api/v2
      title: TEST

spec:
  type: openapi
  lifecycle: published
  owner: gist
  definition:
    $text: ./rds-oas.yaml