apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rds-rest-api
  description: Daňové subjekty REST API
  tags:
    - rest
  links:
    - url: https://registr.cz/api/v1
      title: PROD
    - url: https://registr-test.cz/api/v1
      title: TEST


spec:
  type: openapi
  lifecycle: retired
  owner: gist
  definition:
    $text: ./rds-oas.yaml